//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Belt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Belt()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int BeltId { get; set; }
        public string BeltName { get; set; }
        public string BeltImage { get; set; }
        public Nullable<int> BeltTypeId { get; set; }
        public Nullable<int> BeltColorId { get; set; }
        public Nullable<int> BeltOccasionId { get; set; }
        public Nullable<int> BeltSeasonId { get; set; }
        public string BeltNotes { get; set; }
    
        public virtual BeltColor BeltColor { get; set; }
        public virtual BeltOccasion BeltOccasion { get; set; }
        public virtual BeltSeason BeltSeason { get; set; }
        public virtual BeltType BeltType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
