//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeDbEntities : DbContext
    {
        public WardrobeDbEntities()
            : base("name=WardrobeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeltColor> BeltColors { get; set; }
        public virtual DbSet<BeltOccasion> BeltOccasions { get; set; }
        public virtual DbSet<Belt> Belts { get; set; }
        public virtual DbSet<BeltSeason> BeltSeasons { get; set; }
        public virtual DbSet<BeltType> BeltTypes { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<PantColor> PantColors { get; set; }
        public virtual DbSet<PantOccasion> PantOccasions { get; set; }
        public virtual DbSet<Pant> Pants { get; set; }
        public virtual DbSet<PantSeason> PantSeasons { get; set; }
        public virtual DbSet<PantType> PantTypes { get; set; }
        public virtual DbSet<ShirtColor> ShirtColors { get; set; }
        public virtual DbSet<ShirtOccasion> ShirtOccasions { get; set; }
        public virtual DbSet<Shirt> Shirts { get; set; }
        public virtual DbSet<ShirtSeason> ShirtSeasons { get; set; }
        public virtual DbSet<ShirtType> ShirtTypes { get; set; }
        public virtual DbSet<ShoeColor> ShoeColors { get; set; }
        public virtual DbSet<ShoeOccasion> ShoeOccasions { get; set; }
        public virtual DbSet<Sho> Shoes { get; set; }
        public virtual DbSet<ShoeSeason> ShoeSeasons { get; set; }
        public virtual DbSet<ShoeType> ShoeTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
