//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pant()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int PantId { get; set; }
        public string PantName { get; set; }
        public string PantPhoto { get; set; }
        public int PantTypeId { get; set; }
        public int PantColorId { get; set; }
        public Nullable<int> PantSeasonId { get; set; }
        public Nullable<int> PantOccasionId { get; set; }
        public string PantNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
        public virtual PantColor PantColor { get; set; }
        public virtual PantOccasion PantOccasion { get; set; }
        public virtual PantSeason PantSeason { get; set; }
        public virtual PantType PantType { get; set; }
    }
}
