//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sho()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int ShoeId { get; set; }
        public string ShoeName { get; set; }
        public string ShoePhoto { get; set; }
        public Nullable<int> ShoeTypeId { get; set; }
        public Nullable<int> ShoeColorId { get; set; }
        public Nullable<int> ShoeSeasonId { get; set; }
        public Nullable<int> ShoeOccasionId { get; set; }
        public string ShoeNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
        public virtual ShoeColor ShoeColor { get; set; }
        public virtual ShoeOccasion ShoeOccasion { get; set; }
        public virtual ShoeSeason ShoeSeason { get; set; }
        public virtual ShoeType ShoeType { get; set; }
    }
}
